service: minter
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  minter:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post
