app: AUTOMATE-NFT-MINTER
service: AUTOMATE-NFT-MINTER
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  minter:
    handler: handler.minter
    events:
      - httpApi:
          path: /api/v1/minter
          method: post

plugins:
  - serverless-offline
